<a href="https://colab.research.google.com/github/divyadarshini11/LLM-Projects/blob/main/Word_Embedding_using_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
corpus=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
corpus

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
vocabulary_size = 1000

In [ ]:
one_hot_representation = [one_hot(words,vocabulary_size) for words in corpus]
print(one_hot_representation)

[[630, 2, 791, 265], [630, 2, 791, 90], [630, 69, 791, 929], [719, 524, 206, 130, 884], [719, 524, 206, 130, 405], [310, 630, 103, 791, 586], [289, 893, 275, 130]]


In [ ]:
from tensorflow.keras.layers import Embedding, Flatten
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
max_words_corpus = []
for i in range (len(corpus)):
  max_words_corpus.append(len(corpus[i].split()))
sent_length = max(max_words_corpus)
print(sent_length)

5


In [ ]:
embedded_corpus = pad_sequences(one_hot_representation,padding='pre',maxlen=sent_length)
print(embedded_corpus)

[[  0 630   2 791 265]
 [  0 630   2 791  90]
 [  0 630  69 791 929]
 [719 524 206 130 884]
 [719 524 206 130 405]
 [310 630 103 791 586]
 [  0 289 893 275 130]]


In [ ]:
## Take any dimension, since dataset is small, 10 is taken
## each word is represented in 10 x 1 vector size
dim = 10

In [ ]:
model = Sequential()
model.add(Embedding(vocabulary_size,dim))
model.compile('adam','mse')

In [ ]:
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_12 (Embedding)        │ (None, 5, 10)          │        10,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,000 (39.06 KB)

 Trainable params: 10,000 (39.06 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
embedded_corpus[0]

array([  0, 630,   2, 791, 265], dtype=int32)

In [ ]:
model.predict(np.expand_dims(embedded_corpus[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[[-0.03009794,  0.00562538,  0.0460328 , -0.04000401,
         -0.04756339, -0.04215037,  0.01554015, -0.01612139,
          0.02613289, -0.01209482],
        [ 0.00236921,  0.01119497,  0.00365765, -0.00093289,
          0.02535966, -0.04214375,  0.03202097,  0.00427018,
         -0.01681857,  0.01789561],
        [-0.00332937,  0.01876699, -0.00722075, -0.03551773,
          0.01135454,  0.02443656, -0.02087503,  0.01692355,
         -0.04016558, -0.02177131],
        [ 0.02191112, -0.01660373, -0.04543627,  0.0485408 ,
          0.01593405, -0.02249298, -0.04439706,  0.02415207,
          0.04212452, -0.00632202],
        [ 0.00267086, -0.02081205,  0.04302008, -0.0025622 ,
         -0.02529146, -0.03979089, -0.01357239,  0.02392355,
         -0.01301067, -0.03438805]]], dtype=float32)

In [ ]:
model.predict(embedded_corpus)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step


array([[[-0.03009794,  0.00562538,  0.0460328 , -0.04000401,
         -0.04756339, -0.04215037,  0.01554015, -0.01612139,
          0.02613289, -0.01209482],
        [ 0.00236921,  0.01119497,  0.00365765, -0.00093289,
          0.02535966, -0.04214375,  0.03202097,  0.00427018,
         -0.01681857,  0.01789561],
        [-0.00332937,  0.01876699, -0.00722075, -0.03551773,
          0.01135454,  0.02443656, -0.02087503,  0.01692355,
         -0.04016558, -0.02177131],
        [ 0.02191112, -0.01660373, -0.04543627,  0.0485408 ,
          0.01593405, -0.02249298, -0.04439706,  0.02415207,
          0.04212452, -0.00632202],
        [ 0.00267086, -0.02081205,  0.04302008, -0.0025622 ,
         -0.02529146, -0.03979089, -0.01357239,  0.02392355,
         -0.01301067, -0.03438805]],

       [[-0.03009794,  0.00562538,  0.0460328 , -0.04000401,
         -0.04756339, -0.04215037,  0.01554015, -0.01612139,
          0.02613289, -0.01209482],
        [ 0.00236921,  0.01119497,  0.00365765, -0